### ISSUE TITLE
In creative mode, please fix the mod so that it can fit in the box by dragging the shulker box with the mouse while pressing down the key

### ISSUE THREAD

**Issue by ghost** [Kira-NT/packed-inventory#11]
In creative mode, please fix the mod so that it can fit in the box by dragging the shulker box with the mouse while pressing down the key

**Comment by Kira-NT** [comment]
There are two types of creative inventories: the "Creative Inventory" *(the one with tabs from which you can take unlimited items)* and the "Creative Survival Inventory" *(the one where you can equip armor)*. The problem is that the first one is quite old, I would even call it legacy. Back in the day, some genius decided to implement it almost entirely on the client-side, and since Packed Inventory is a server-side mod *(except for the keybindings, which are created to send commands to the server)*, it's impossible for it to manipulate or even recognize a client-side inventory. To "fix" this issue, I would need to fix Minecraft itself, specifically its legacy code. And I firmly believe that this is beyond the scope of this mod. Especially when users can easily switch to the Creative Survival Inventory *(by pressing the chest icon in the regular creative inventory)*, which is server-side and therefore already compatible with Packed Inventory.
