### ISSUE TITLE
[Feature request] insert/extract

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Kira-NT/packed-inventory#4]
Hold a stack of items and mouse-over an item with an inventory, then right-click/use hotkey to insert the stack into the inventory.

Mouse-over an item with an inventory and shift-right-click/use hotkey to extract the first stack in the inventory into the player's inventory.

**Comment by Kira-NT** [comment]
I received this suggestion on CurseForge:

> Oh gosh, I still remember a mod from 1.6.4. Cardboard boxes or something. It had a feature which allowed you to open the boxes right in your inventory, but in an INCREDIBLY fancy way: It would have a tooltip like this, but it existed as a real inventory overlayed on your own, letting you manage your boxes without even having to go to a separate screen.

I think I will implement something like these interactive tooltips

**Comment by supersaiyansubtlety** [comment]
I don't understand how that's functionally different from just opening the actual screen as you currently do?

**Comment by Kira-NT** [comment]
It is different. Basically, you can interact with more than 2 inventories at the same time. But let's get back to your suggestion. Actually, it would be nice to implement a feature similar to the bundle:

> To place items inside a bundle, either (1) pick up the bundle in the inventory and right-click on the item(s) to be placed inside or (2) pick up the item(s) and right-click on the bundle. When placing bundles inside another bundle, the interface uses the first method: picking up Bundle A and right clicking on Bundle B attempts to store Bundle B inside A.
> 
> Bundles can be used inside the inventory to take out the last item put in. In this way, items are accessible LIFO (last in, first out). When used outside the inventory, it dumps all the items out into the world. 

As I said in #2, `RMB` is a hard no-no, but I can extend functionality of the key bind that is currently named "Open edit screen":
 - If the inventory is not open, it will try to access an item in the active hotbar slot *(like it does right now)*
 - Otherwise, if the cursor stack is not empty, it will try to suck item in/out of the selected inventory item
 - If the attempt fails (or if the cursor stack is empty), it will try to open the edit screen *(like it does right now)*

**Comment by Kira-NT** [comment]
I'm actually very happy with the feature so far. Thank you for suggesting it!

![quick_transfer-shulker_box](https://user-images.githubusercontent.com/40232067/181506278-ac37ffe7-1ab7-4b2e-9894-f8560e6e1f41.gif)
