### ISSUE TITLE
Crash even the mod alone in 1.18.1

### ISSUE THREAD

**Issue by Atomo93** [Kira-NT/packed-inventory#9]
Is the version or what, I downloaded through curseforge app
[latest.log](https://github.com/Kir-Antipov/packed-inventory/files/10423200/latest.log)

**Comment by Kira-NT** [comment]
> Crash even the mod alone in 1.18.1

As it should, because the version you are referring to was made for 1.18.2 *(the latest available patch for 1.18 release)* and was tested solely on it.

What you *could* try to do is:

1) Download the latest available release of the mod for Minecraft 1.18 ([0.2.2+1.18.2](https://www.curseforge.com/minecraft/mc-mods/packed-inventory/files/3916749))
2) Open the mod's jar as a regular zip file in any program you like
3) Open the `META-INF` folder and delete `jars` one there
4) Go back to the root of the zip archive and open `fabric.mod.json`. Delete `jars` there too
5) Save the changes
6) Install a suitable version of Fabric API for Minecraft 1.18.1
7) Try to boot your game

1.18.2 is not that different from 1.18.1, so maybe the mod will be able to run in that environment with these simple changes
